name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  # JWT
  dart_jsonwebtoken: ^2.7.1
  # .env
  envied: ^0.3.0
  #  toJson fomJson
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  # api server
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  lints: ^2.0.0
  test: ^1.16.0
